### ISSUE TITLE
How do you compile this?

### ISSUE THREAD

**Issue by timkoers** [asturel/android_device_huawei_s7#1]
Should this repo be copied over the CM10.1 repo and then be build? Or is this the full Android build system?

I have tried several things, but none of them worked.

**Comment by asturel** [comment]
this should go to device tree: android/device/huawei/s7, but you need to apply the patches to the android from the 'patches' directory otherwise it wont compile/work

**Comment by timkoers** [comment]
Aha, I think that that might be the problem. Thanks!`
And those patches include device related things?
